server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oa?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: '0000'
    hikari:
      pool-name: DatebookHikariCP
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis-plus:
    configuration:
      map-underscore-to-camel-case: false

logging:
  level:
    games.highping.server.mapper: debug

jwt:
  tokenHeader: Authorization
  secret: oa-secret
  expiration: 604800
  tokenHead: Bearer